In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [23]:
X,y=np.arange(10).reshape(5,2), range(5)
X,list(y)

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),
 [0, 1, 2, 3, 4])

In [15]:
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=.3, random_state=42)

In [17]:
X_train

array([[4, 5],
       [0, 1],
       [6, 7]])

In [18]:
X_test

array([[2, 3],
       [8, 9]])

In [21]:
y_train

[2, 0, 3]

In [22]:
y_test

[1, 4]